// カテゴリーの並び順とラベル。build.js と catalog.js が共有する。
module.exports = [
  ['表紙',            'cover'],
  ['目次',            'toc'],
  ['中扉',            'section'],
  ['学長メッセージ',   'message'],
  ['学校紹介・特色',   'about'],
  ['学科・コース紹介', 'department'],
  ['カリキュラム',     'curriculum'],
  ['授業・実習・教員', 'class'],
  ['在学生インタビュー','student'],
  ['キャンパスライフ', 'campuslife'],
  ['施設・キャンパス', 'facility'],
  ['進路・就職',       'career'],
  ['卒業生',           'og'],
  ['作品・成果',       'works'],
  ['国際交流・留学',   'global'],
  ['資格・免許',       'license'],
  ['学費・奨学金',     'support'],
  ['入試',             'admission'],
  ['オープンキャンパス','opencampus'],
  ['アクセス・学校概要','access'],
  ['よくある質問',     'faq'],
  ['裏表紙',           'backcover'],
  ['見開き',           'spread'],
  ['募集要項',         'guidelines'],
];
